enum AppStrings {
    static let appName = "ReleasePilot"
    static let versionPill = "V4.0"
    static let navDashboard = "Dashboard"
    static let navApps = "Apps"
    static let navHistory = "History"
    static let navSettings = "Settings"
    static let yourApps = "Your Apps"
    static let proPlan = "Pro Plan"
    static let proRenew = "Renews on 2025-12-31"
    static let managePlan = "Manage Plan"
    static let userName = "张小明"
    static let userEmail = "zhang@example.com"

    static let readiness = "发布准备度"
    static let reviewTime = "预计审核时间"
    static let reviewRisk = "审核风险"
    static let contentCompletion = "内容完成度"
    static let aiScore = "AI 评分"
    static let releaseFlow = "发布流程"
    static let todayTasks = "今日待处理"
    static let suggestions = "建议优化"
    static let currentBuild = "当前构建版本"
    static let screenshotPreview = "截图预览"
    static let submitTitle = "准备提交 App Store 审核"
    static let submitSubtitle = "提交后，预计 24–48 小时内完成审核"
    static let submitReview = "提交审核"
    static let submitInfo = "提交信息"
    static let postReleasePlan = "发布后计划"

    static let copilotTitle = "AI Copilot"
    static let copilotBeta = "Beta"
    static let copilotSubtitle = "你的发布智能助手"
    static let chat = "对话"
    static let advice = "建议"
    static let userPrompt = "帮我生成一份专业的审核备注"
    static let reviewNoteTitle = "审核备注（中文）"
    static let copy = "复制"
    static let applyReviewNote = "应用到审核备注"
    static let inputPlaceholder = "询问任何关于发布的问题..."

    static let confirmSubmitTitle = "确认提交审核？"
    static let confirmSubmitMessage = "提交后将使用当前构建、元数据、截图和审核信息。"
    static let cancel = "取消"
    static let confirmSubmit = "确认提交"
}
