enum AppStrings {
    static let appName = "ReleasePilot"
    static let versionPill = "V4.0"
    static let navDashboard = "Dashboard"
    static let navApps = "Apps"
    static let navHistory = "History"
    static let navSettings = "Settings"
    static let yourApps = "Your Apps"
    static let proPlan = "Pro Plan"
    static let proRenew = "Renews on 2025-12-31"
    static let managePlan = "Manage Plan"
    static let userName = "张小明"
    static let userEmail = "zhang@example.com"

    static let readiness = "发布准备度"
    static let reviewTime = "预计审核时间"
    static let reviewRisk = "审核风险"
    static let contentCompletion = "内容完成度"
    static let aiScore = "AI 评分"
    static let releaseFlow = "发布流程"
    static let todayTasks = "今日待处理"
    static let suggestions = "建议优化"
    static let currentBuild = "当前构建版本"
    static let screenshotPreview = "截图预览"
    static let submitTitle = "准备提交 App Store 审核"
    static let submitSubtitle = "提交后，预计 24–48 小时内完成审核"
    static let submitReview = "提交审核"
    static let submitInfo = "提交信息"
    static let postReleasePlan = "发布后计划"

    static let copilotTitle = "AI Copilot"
    static let copilotBeta = "Beta"
    static let copilotSubtitle = "你的发布智能助手"
    static let chat = "对话"
    static let advice = "建议"
    static let userPrompt = "帮我生成一份专业的审核备注"
    static let reviewNoteTitle = "审核备注（中文）"
    static let copy = "复制"
    static let applyReviewNote = "应用到审核备注"
    static let inputPlaceholder = "询问任何关于发布的问题..."

    static let confirmSubmitTitle = "确认提交审核？"
    static let confirmSubmitMessage = "提交后将使用当前构建、元数据、截图和审核信息。"
    static let cancel = "取消"
    static let confirmSubmit = "确认提交"

    // Debug Panel
    static let debugTitle = "接口调试面板"
    static let debugTotalRequests = "总请求数"
    static let debugDuplicateGroups = "重复接口"
    static let debugEndpoint = "接口"
    static let debugMethod = "方法"
    static let debugCount = "请求次数"
    static let debugStatus = "状态码"
    static let debugDuration = "耗时"
    static let debugParams = "参数"
    static let debugLastTime = "最近请求"
    static let debugNoRequests = "暂无接口请求记录"
    static let debugNoRequestsHint = "同步 App Store Connect 数据后，请求记录将在此显示"
    static let debugWarningDuplicate = "重复请求"
    static let debugWarningSerious = "严重重复"
    static let debugWarningCritical = "极高风险"
    static let debugWarningCriticalMessage = "同一接口+参数被调用超过 4 次，可能触发苹果风控！"
    static let debugWarningSeriousMessage = "同一接口+参数被调用 3~4 次，存在被风控的风险"
    static let debugWarningDuplicateMessage = "同一接口+参数被重复调用，建议检查逻辑"
    static let debugClearAll = "清空记录"
    static let debugRiskLevel = "风险等级"
}
